language: node_js
node_js:
  - "0.12"
install:
  - npm install
  - npm run pkg
after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
notifications:
  email:
    - lenguyensy@gmail.com
# whitelist
branches:
  only:
    - master