language: node_js
node_js:
  - "0.12"
install:
  - npm install
  - debug=1 npm run pkg
after_success:
  - .travis/push.sh
notifications:
  email:
    - lenguyensy@gmail.com
# whitelist
branches:
  only:
    - master