language: node_js
node_js:
  - "0.12"
install:
  - npm install
  - npm run pkg
after_success:
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git push origin master
# whitelist
branches:
  only:
    - master